gitGraph
    commit id: "CREATE TABLE inventory"
    commit id: "INSERT Widget,Gadget,Gizmo"
    branch branch_a
    commit id: "INSERT Doodad"
    commit id: "UPDATE Widget qty=150"
    branch branch_c
    commit id: "INSERT Whatchamacallit"
    commit id: "DELETE Gizmo"
    checkout main
    branch branch_b
    commit id: "DELETE Gadget"
    commit id: "INSERT Thingamajig"
